  INSERT INTO EMPLOYEE_DATA 
( FIRST_NAME, LAST_NAME,
  GENDER,DOB,NATIONALITY,MARITAL_STATUS,
  PHONE,SUBDIVISION,
  STATUS,SUSPEND_DATE,HIRED_DATE,
  GRADE,DIVISION,
  EMAIL,LOCATION,
  AVATAR)

 VALUES 
 
 (  'Jorge', 'Wills',
    'Male','1988-11-23','Australia','Married',
	'021 002285','CDC',
	'Full Time','2017-10-13','2017-10-13',
	'SE-AP','SWD-Green',
	'mail@gee.com','Jakarta' ,
     FILE_READ('D:/workspace/rms/src/images/128.JPG')
  ); 
   

 INSERT INTO EMPLOYEE_DATA 
( FIRST_NAME, LAST_NAME,
  GENDER,DOB,NATIONALITY,MARITAL_STATUS,
  PHONE,SUBDIVISION,
  STATUS, SUSPEND_DATE,HIRED_DATE,
  GRADE,DIVISION,
  EMAIL,LOCATION,AVATAR )

 VALUES 
 
 ( 'Cecill', 'Natalie',
    'Female','1988-06-30','Japan','Married',
	'021 346346','CDC',
	'Full Time','2017-10-13','2017-10-13',
	'SE-PG','SWD-Green',
	'mail@gee.com','Bali',
	 FILE_READ('D:/workspace/rms/src/images/2.JPG')
  );  
  
  
INSERT INTO GRADE_HISTORY ( EMPLOYEE_ID,DS,CURRENT_GRADE,START_DATE,END_DATE)
VALUES ( (SELECT EMP_ID FROM EMPLOYEE_DATA WHERE EMP_ID=1),
'DS6','SE-PG','2015-1-23','2015-9-23');
 